framework:
  cache:
    # Redis
    # pools:
    #   redis_cache:
    #     adapter: cache.adapter.redis
    #     default_redis_provider: redis://localhost
    #     provider: "%env(REDIS_URL)%"

    # Filesystem
    # pools:
    #   file_cache:
    #     adapter: cache.adapter.filesystem
    #     default_lifetime: 3600
    #     public: false
