when@dev:
  framework:
    cache:
      pools:
        redis_cache_pool_dev:
          default_lifetime: 3600
          adapter: cache.adapter.redis
          # adapter: cache.adapter.filesystem
          provider: "redis://redisKey@ip:6379" # "%env(REDIS_URL)%"

when@prod:
  framework:
    cache:
      pools:
        redis_cache_pool_prod:
          default_lifetime: 10800
          adapter: cache.adapter.redis
          # adapter: cache.adapter.filesystem
          provider: "redis://redisKey@ip:6379" # "%env(REDIS_URL)%"
