version: "3.1"
services:
  webserver:
    image: "nginx:alpine"
    restart: always
    container_name: online_learning_webserver
    working_dir: /application
    volumes:
      - ".:/application"
      - "./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8800:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: online_learning_php-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /application
    expose:
      - 9000
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - ".:/application"
      - "./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini"
      - "./phpdocker/php-fpm/error_reporting.ini:/etc/php/8.2/fpm/conf.d/error_reporting.ini"

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    restart: always
    container_name: online_learning_phpmyadmin
    ports:
      - "8801:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=online_learning_mariadb

  nodejs:
    image: "node:20.9"
    restart: always
    container_name: online_learning_nodejs
    working_dir: /application
    volumes:
      - ".:/application"
    ports:
      - "8802:3000"

  mariadb:
    image: "mariadb:11.0"
    restart: always
    container_name: online_learning_mariadb
    working_dir: /application
    volumes:
      - ".:/application"
    environment:
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - "8803:3306"
