version: "3.1"
services:
  cache:
    image: "redis:7.2-alpine"
    container_name: online_learning_cache
    ports:
      - "6379:6379"

  mysql:
    image: "mariadb:11.0"
    container_name: online_learning_mysql
    working_dir: /application
    volumes:
      - ".:/application"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_ROOT_USER=root
      - MARIADB_DATABASE_NAME=jagaadonline
    ports:
      - "3306:3306"

  adminer:
    image: "adminer:latest"
    container_name: online_learning_db_admin
    ports:
      - "8801:8801"

  nginx:
    image: "nginx:alpine"
    container_name: online_learning_webserver
    working_dir: /application
    volumes:
      - ".:/application"
      - "./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8800:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: online_learning_php-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /application
    expose:
      - 9000
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - ".:/application"
      - "./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini"

  mailer:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
